add release_note check

diff --git a/oemcheck b/oemcheck
--- a/oemcheck
+++ b/oemcheck
@@ -246,6 +246,11 @@ checkpattern(){
 		echo -e "\e[1;31mERROR: cfg file email address error!\e[0m"
 	#todo	exit
 	fi
+	ls -l $tardir/$serdisName/release_note 1>/dev/null 2>/dev/null
+	if [ $? -eq 0 ];then
+		echo -e "\e[1;31mERROR: release_note file exists!\e[0m"
+		#todo exit
+	fi
 
 }
 
